name: Crypto AI Backtest & Alerts

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backtest script
      run: |
        python crypto_ai_backtest_multi.py

    - name: Upload artifacts (stats, charts, signals)
      uses: actions/upload-artifact@v3
      with:
        name: backtest-artifacts
        path: |
          *.csv
          *.png
          signals.txt

    - name: Check for signals
      id: check_signals
      run: |
        if [ -f signals.txt ]; then echo "found=true" >> $GITHUB_OUTPUT; else echo "found=false" >> $GITHUB_OUTPUT; fi

    - name: Send email if signals exist
      if: steps.check_signals.outputs.found == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASS }}
        subject: "Crypto Bot Signals"
        to: ${{ secrets.SIGNAL_EMAIL }}
        from: "crypto-bot@users.noreply.github.com"
        body_file: signals.txt

    - name: Send IFTTT push if signals exist
      if: steps.check_signals.outputs.found == 'true'
      run: |
        payload="$(cat signals.txt | sed 's/"/\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')"
        curl -s -X POST "https://maker.ifttt.com/trigger/${{ secrets.IFTTT_EVENT }}/with/key/${{ secrets.IFTTT_KEY }}" -H "Content-Type: application/json" -d "{"value1":"$payload"}"
